#requires -Version 7.4
# Prunes build/test leftovers from the source checkout so only the newest release and
# the tooling needed to rebuild stay on disk. Everything removed here is regenerated by
# scripts/verify.ps1 or scripts/build.ps1; nothing tracked by Git is touched.
#
#   .\scripts\clean-workspace.ps1            # keep the newest release package, delete the rest
#   .\scripts\clean-workspace.ps1 -WhatIf    # list what would be deleted
#   .\scripts\clean-workspace.ps1 -KeepReleases 2
param([int]$KeepReleases = 1, [switch]$WhatIf)
$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
$runtime = Join-Path $projectRoot '.runtime'
if (Get-Process java -ErrorAction SilentlyContinue) { throw 'A Java process is running. Finish or stop builds, tests and the dev instance first.' }

# Tooling under .runtime that later builds and the release procedure still use.
$keepRuntime = @('mysql', 'pnpm-shim', 'dev', 'cdx-schemas', 'bom-validator-classes', 'maven-central-settings.xml', 'build.cmd', 'run-release-build.ps1')
$keepExtensions = @('.ps1', '.mjs', '.java', '.xml', '.cmd')
$targets = [Collections.Generic.List[string]]::new()
foreach ($entry in Get-ChildItem -LiteralPath $runtime -Force) {
    if ($keepRuntime -contains $entry.Name -or $entry.Name -like 'sbom-*') { continue }
    if (-not $entry.PSIsContainer -and $keepExtensions -contains $entry.Extension) { continue }
    $targets.Add($entry.FullName)
}
# Release packages: newest $KeepReleases directory+zip pairs stay, older ones and their sidecar JSONs go.
$releases = Join-Path $projectRoot 'artifacts/releases'
if (Test-Path -LiteralPath $releases) {
    $zips = @(Get-ChildItem -LiteralPath $releases -Filter '*.zip' -File | Sort-Object LastWriteTime -Descending)
    $keep = @($zips | Select-Object -First $KeepReleases | ForEach-Object { $_.BaseName })
    foreach ($entry in Get-ChildItem -LiteralPath $releases -Force) {
        $base = if ($entry.PSIsContainer) { $entry.Name } else { ($entry.Name -replace '\.(zip|acceptance\.json|dependencies\.json|sbom\.json)$', '') }
        if ($keep -notcontains $base) { $targets.Add($entry.FullName) }
    }
}
foreach ($relative in @('frontend/test-results', 'frontend/playwright-report', 'backend/target/failsafe-reports', 'backend/target/surefire-reports')) {
    $path = Join-Path $projectRoot $relative
    if (Test-Path -LiteralPath $path) { $targets.Add($path) }
}
$superpowers = Join-Path $projectRoot '.superpowers'
if (Test-Path -LiteralPath $superpowers) { Get-ChildItem -LiteralPath $superpowers -Recurse -File -Filter '*.log' | ForEach-Object { $targets.Add($_.FullName) } }

$bytes = 0
foreach ($target in $targets) {
    $item = Get-Item -LiteralPath $target -Force
    $bytes += if ($item.PSIsContainer) { (Get-ChildItem -LiteralPath $target -Recurse -File -Force | Measure-Object Length -Sum).Sum } else { $item.Length }
}
if ($WhatIf) { $targets | ForEach-Object { Write-Output "would delete $_" } }
else { foreach ($target in $targets) { Remove-Item -LiteralPath $target -Recurse -Force } }
$verb = if ($WhatIf) { 'Would delete' } else { 'Deleted' }
$gigabytes = [math]::Round($bytes / 1GB, 1)
Write-Output "$verb $($targets.Count) entries, $gigabytes GB."
